#!/usr/bin/env python3
"""Washington: LOCAL real estate excise tax rate per city / unincorporated
county — Department of Revenue "Local Real Estate Excise Tax Rates" PDF
(form 84-0013, re-issued when a rate changes) → lib/data/waLocalReet.js.
County FIPS = 53 + (2 × the REET county number − 1): both follow the
alphabetical county order (King = REET 17 = FIPS 53033).
  python3 scripts/build-wa-reet.py https://dor.wa.gov/sites/default/files/2026-03/84-0013-May26_REET.pdf
"""
import io, json, os, re, sys, urllib.request
import pypdf
url = sys.argv[1]
raw = urllib.request.urlopen(urllib.request.Request(url, headers={"User-Agent": "Mozilla/5.0 (Pradixium data build)"}), timeout=120).read()
text = "\n".join(p.extract_text() for p in pypdf.PdfReader(io.BytesIO(raw)).pages)
eff = re.search(r"Rates Effective ([A-Z][a-z]+ \d+, \d{4})", text).group(1)
out = {}
for l in text.splitlines():
    m = re.match(r"^([A-Z][A-Za-z ]+?) (.+?) (\d{4}) (\d\.\d\d)%\s*$", l.strip())
    if not m: continue
    county, place, code, rate = m.groups()
    fips = "53" + str(2 * int(code[:2]) - 1).zfill(3)
    if "Unincorp" in place: key = f"{fips}|*"
    else: key = f"{fips}|" + re.sub(r"\s+in \w[\w ]* County$|\s*\(City\)$", "", place).lower()
    out[key] = float(rate)
assert out.get("53033|seattle") == 0.5 and out.get("53033|*") == 0.5, "check failed"
p = os.path.join(os.path.dirname(__file__), "..", "lib", "data", "waLocalReet.js")
open(p, "w").write(f"// GENERATED by scripts/build-wa-reet.py — WA DOR local REET rates effective {eff}\nexport const WA_LOCAL_REET = {{ effective: {json.dumps(eff)}, url: {json.dumps(url)}, rates: {json.dumps(out, separators=(',', ':'))} }};\n")
print(eff, len(out), "locations; seattle", out["53033|seattle"], "tacoma", out.get("53053|tacoma"), "spokane", out.get("53063|spokane"))
